services:
  postgres:
    image: bitnami/postgresql:15
    container_name: postgres-db
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: capybachallenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  backend:
    build: ./backend
    container_name: capyba_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://docker:docker@postgres:5432/capybachallenge
      JWT_SECRET: 744ca06ab8ada5553e7bd55d8db5da27e1a2f28833b228b37f1831be3e739a14d57b8a6ee1224a0fcde51ddae7b9510796e3e529638507c3a4cc0d834f646fc2
      JWT_EXPIRATION: 1h
      JWT_EMAIL_TOKEN: 3a9d487761dac5d7c9f00050a50fe1aa65eeab1baa8bd990808cff2d94417fe6d63c0caed4ce43307bbc8b8d875efddd7b0f5c4b6f6fe487d986b717132154f8
      JWT_EMAIL_EXPIRATION: 5m
      EMAIL: vlidington@gmail.com
      EMAIL_PASSWORD: hdpa xtrt liaj bijb

  frontend:
    build: ./frontend
    container_name: capyba_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
